// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>


[id='running-a-fruit-inventory-application_{context}']
= Running a fruit inventory application

The Red Hat Developer Launcher enables you to build and deploy applications on OpenShift.
In this procedure, you deploy an example Node.js application that is pre-configured to provide a REST API that returns a list of fruit.

.Procedure

. Log in to the link:https://developers.redhat.com/launch/[Red Hat Developer Launcher].

. Select the *LAUNCH YOUR PROJECT*.

. Enter a name for your application and select *Continue*.

. Select *Code Locally, Build and Deploy* to deploy the application on a hosted OpenShift instance. Click the blue down arrow to continue.

. Select *CRUD* from the list of missions and *Node.js* from the list of runtimes. Accept the default version of Node.js. Click the blue down arrow to continue.

. Select the *Log in & Authorize Account* button and give OpenShift permissions to your GitHub account. Click the blue down arrow to continue.

. Review your configuration and select *Set Up Application* to create an OpenShift deployment.
